# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            snippets.d
tagline:          'lost in code'
description:      ''
url:              http://derfian.github.io
baseurl:          /

author:
  name:           'Karl Mikaelsson'
  url:            https://twitter.com/derfian

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/derfian/derfian.github.io
