# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            snippets.d
tagline:          'lost in code'
description:      'Karl writes about code'
url:              http://derfian.github.io
baseurl:          /

author:
  name:           'Karl Mikaelsson'
  email:          derfian@lysator.liu.se
  url:            https://twitter.com/derfian

paginate:         5

# Custom vars
github:
  repo:           https://github.com/derfian/derfian.github.io
